### ISSUE TITLE
No Matches Error

### ISSUE THREAD

**Issue by azarzosa** [lavalink-devs/youtube-source#12]
Bot using Lavaplayer now never finds tracks, even with the URL:
![image](https://github.com/lavalink-devs/lavaplayer/assets/15789477/79dd43bd-0c2d-46bf-962e-ac47be787d95)
(The resulting message of the noMatches() method of AudioLoadResultHandler() being called, even with the full youtube URL being sent)

**Comment by lMolMol** [comment]
same issue here

**Comment by devoxin** [comment]
Please state what clients you're using and your youtube-source version

**Comment by devoxin** [comment]
Yes, `youtube-source` replaces the built-in source. There are deprecation warnings everywhere stating this

**Comment by azarzosa** [comment]
Understood, my apologies for not keeping up. Just a bit confused on how to implement it to a Maven project.

**Comment by superjgonzo** [comment]
Not sure if this was solved but I was able to add the dependency via Maven like:
```
<repository>
    <id>ll-releases</id>
    <name>Lavalink Releases</name>
    <url>https://maven.lavalink.dev/releases</url>
</repository>

<dependency>
    <groupId>dev.lavalink.youtube</groupId>
    <artifactId>common</artifactId>
    <version>1.3.0</version>
</dependency>
```
