### ISSUE TITLE
Im getting this error "Connect timed out"

### ISSUE THREAD

**Issue by KasaiKonoru** [lavalink-devs/youtube-source#17]
**Lavalink** 

Version:        3.7.12
Build time:     05.05.2024 20:58:03 UTC
Branch          HEAD
Commit:         98115f4
Commit time:    05.05.2024 20:43:02 UTC
JVM:            18.0.2-ea
Lavaplayer      1.5.4
---------------------------------------------------

youtube-source
plugin 'youtube-plugin': version 4aff44d95d3eff64c4e978fd305ae4f8d12f4cc6

![grafik](https://github.com/lavalink-devs/youtube-source/assets/45830738/be625593-a2ea-4652-8616-86606d60c181)
![grafik](https://github.com/lavalink-devs/youtube-source/assets/45830738/e7d0d442-391e-4a24-b054-42522a00c515)

**Comment by devoxin** [comment]
This is not an issue with the source. This is an issue with your network configuration or routing.

**Comment by KasaiKonoru** [comment]
but the tunnel is working. :ccc

**Comment by KasaiKonoru** [comment]
and I can ping everything

**Comment by devoxin** [comment]
Again, this is not a source issue. All the source does is select an IP and make a request. There is nothing to be fixed here, or rather, nothing we can fix. This is entirely on your system configuration and routing.

**Comment by KasaiKonoru** [comment]
Ok
