### ISSUE TITLE
Add retry option when getting 403 sometime.

### ISSUE THREAD

**Issue by manybaht** [lavalink-devs/youtube-source#24]
What feature would you like to be added? Give a brief summary.

What would you like this feature to do? Feel free to go into detail, explaining the finer points may help with implementing if your idea is accepted.

Add a retry option or use the retryLimit from the rateLimit config block. Even with /48, I still occasionally receive 403 errors. It would be nice if it tried to retry the request again.

**Comment by devoxin** [comment]
Already used.
https://github.com/lavalink-devs/youtube-source/blob/main/plugin/src/main/java/dev/lavalink/youtube/plugin/YoutubePluginLoader.java#L167-L178
