### ISSUE TITLE
Bot enters the voice channel, fetches the song but doesn't play it and exits

### ISSUE THREAD

**Issue by Gabry2790** [lavalink-devs/youtube-source#28]
### Basic Troubleshooting

- [X] I have checked for similar issues, and my issue is not a duplicate. (Check closed issues as well)
- [X] I have checked for pull requests that may already address my issue.
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [X] My issue is reproducible with IPv6 rotation.
- [X] I have confirmed that my issue is reproducible with the minimum viable clients (MUSIC, WEB and TVHTML5EMBEDDED)

### Version of youtube-source

1.3.0

### The search query, URL, playlist or video ID that triggered the issue

Every search query or URL

### Code Example

N/A

### Exception and Stacktrace

These are the entire logs of Lavalink with the plugin
[spring.log](https://github.com/user-attachments/files/16119503/spring.log)

**Comment by devoxin** [comment]
> 2024-07-07T13:41:00.825Z  INFO 28 --- [main] d.l.youtube.plugin.YoutubePluginLoader   : YouTube source initialised with clients: WEB_REMIX, WEB, ANDROID 
2024-07-07T13:41:00.825Z DEBUG 28 --- [main] d.l.youtube.plugin.YoutubePluginLoader   : No ratelimit config found, skipping setup of route planner

You *still* have **not** followed what I have stated in https://github.com/lavalink-devs/Lavalink/issues/1055#issuecomment-2211779849

Enable IP rotation.
Enable more clients.

**Comment by Gabry2790** [comment]
I tried, I activated all the clients and the IP rotation, but wasn't working so I revert changes

**Comment by devoxin** [comment]
"Wasn't working" is the vaguest information you could provide here. Was the error message the same? Which IPv6 provider did you use? What was the subnet size? Have you tried other hosts/ASNs?

**Comment by Gabry2790** [comment]
1. Was the error message the same?
Everytime was video unavailable

2. Which IPv6 provider did you use?
I used IPv4 with "LoadBalance" and "RotateOnBan" strategy

3. What was the subnet size?
The subnet size was 32bits

4. Have you tried other hosts/ASNs?
No, I didn't even think about it

**Comment by devoxin** [comment]
> I used IPv4 with "LoadBalance" and "RotateOnBan" strategy

IPv4 is heavily discouraged. There is a reason we encourage usage of IPv6 over v4. With v6, you get a lot more addresses. a `/48` is generally recommended as the minimum because there have been scenarios in the past where an entire /64 gets banned.

You can't combine strategies so I'm not sure what you mean by usage of both. `RotateOnBan` has been subject to internal discussion and this strategy will most likely be deprecated as it's not ideal to get an IP banned in the first place, additionally, the checks for a ban aren't really applicable anymore as there are different ways YT issues bans now. I would personally recommend `RotatingNanoSwitch`.

> size was 32bits
For an IPv4 this is literally one address so that is not rotation. You need multiple to successfully rotate.

Set up **IPv6 Rotation**, ideally with a **/48**.

**Comment by Gabry2790** [comment]
The problem Is that I am using a free host that uses only IPv4

**Comment by devoxin** [comment]
There are plenty of services out there that will provide a tunnel to allow you to use IPv6.
Read the Lavalink docs for information on this.

**Comment by Gabry2790** [comment]
Ok, thank you and Sorry for annoying you so much 😅

**Comment by MartinItsLinda** [comment]
Also, don't host something you care about on a free provider, even if you buy a €3 a month vps you'll be better off than what any free host gives you.

**Comment by Gabry2790** [comment]
Good to know, but I can't buy any cheap vps because I am a minor and my parents wouldn't buy it for me

**Comment by devoxin** [comment]
FWIW OVH has a dirt cheap VPS for £1/mo https://www.ovhcloud.com/en-gb/vps/

Or see if you can host with a friend or something.
Perhaps further discussion would be better suited for the Discord server regardless

**Comment by Gabry2790** [comment]
Thanks for all the help, have a nice day!

**Comment by Joniii11** [comment]
> FWIW OVH has a dirt cheap VPS for £1/mo https://www.ovhcloud.com/en-gb/vps/
> 
> Or see if you can host with a friend or something. Perhaps further discussion would be better suited for the Discord server regardless

Yes that's true, but they offer just a /128 IPv6 and tunnelbroker blocked (restricted) ovh's ips
