### ISSUE TITLE
add support youtubeconfig (Google Account)

### ISSUE THREAD

**Issue by saya-yukimi** [lavalink-devs/youtube-source#5]
youtubeConfig: 
email: "youtube@gmail.com"
password: "password" 

![image](https://github.com/lavalink-devs/youtube-source/assets/161682134/1aaafab8-ae1d-41b6-a4bd-0ba4f3f017ef)

**Comment by devoxin** [comment]
This most likely won't be happening as the previous method for authenticating accounts was slowly becoming prone to errors (http 400). There's also a lot of code required to support this with, IMO, very little gain, as well as the security implications etc.
