### ISSUE TITLE
Support for WebM Stream

### ISSUE THREAD

**Issue by KagChi** [lavalink-devs/youtube-source#51]
What feature would you like to be added? Give a brief summary.

What would you like this feature to do? Feel free to go into detail, explaining the finer points may help with implementing if your idea is accepted.

...
YouTube sometime sent only WebM with unknown length, this break the plugin. which cannot processed as static source.

**Comment by devoxin** [comment]
It is unlikely this will be supported. However I have noticed some videos being misdetected as livestreams, which is likely why this error is being thrown. I have a fix in the pipeline but I am waiting for further data before I can publish a release.

**Comment by devoxin** [comment]
This is likely resolved in 1.8.3.
