### ISSUE TITLE
reply with "No matches found" for no reason

### ISSUE THREAD

**Issue by Turkidev** [lavalink-devs/youtube-source#55]
### Basic Troubleshooting

- [X] I have checked for similar issues, and my issue is not a duplicate. (Check closed issues as well)
- [X] I have checked for pull requests that may already address my issue.
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [X] My issue is reproducible with IPv6 rotation.
- [X] I have confirmed that my issue is reproducible with the minimum viable clients (MUSIC, WEB and TVHTML5EMBEDDED)

### Version of youtube-source

tested on 1.7.2 and 1.8.2

### The search query, URL, playlist or video ID that triggered the issue

when i try a direct link it works but when i try to search i get "No matches found"

### Code Example

N/A

### Exception and Stacktrace

when i try to search using words i get this

```
INFO 3133875 --- [Lavalink] [ XNIO-1 task-23] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:2pac"
INFO 3133875 --- [Lavalink] [ XNIO-1 task-23] d.l.y.http.YoutubeAccessTokenTracker     : Updating YouTube visitor id succeeded, new one is *********, next update will be after 600 seconds.
INFO 3133875 --- [Lavalink] [ XNIO-1 task-23] lavalink.server.player.AudioLoader       : No matches found
```

when i try using the link i get this
```
INFO 3133875 --- [Lavalink] [ XNIO-1 task-23] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=41qC3w3UUkU"
INFO 3133875 --- [Lavalink] [ XNIO-1 task-23] lavalink.server.player.AudioLoader       : Loaded track 2Pac - Hit 'Em Up (Dirty) (Music Video) HD
INFO 3133875 --- [Lavalink] [ XNIO-1 task-23] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D41qC3w3UUkU
INFO 3133875 --- [Lavalink] [ XNIO-1 task-23] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/ju7cslv4cpjtqjq0/players/1263258540831932477?noReplace=false, payload={"track":{"encoded":"QAABMAMAKjJQYWMgLSBIaXQgJ0VtIFVwIChEaXJ0eSkgKE11c2ljIFZpZGVvKSBIRAANU2V2ZW4gSGlwLUhvcAAAAAAABO24AAs0MXFDM3czVVVrVQABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PTQxcUMzdzNVVWtVAQCbaHR0cHM6Ly9pLnl0aW1nLmNvbS92aS80MXFDM3czVVVrVS9tYXhyZXNkZWZhdWx0LmpwZz9zcXA9LW9heW13RW1DSUFLRU5BRjhxdUtxUU1hOEFFQi1BRy1CNEFDMEFXS0Fnd0lBQkFCR0hJZ1VDZzVNQTg9JnJzPUFPbjRDTEJTR1loZExCMERETmt2R0lXVTZIcDFaMEN4ZmcAAAd5b3V0dWJlAAAAAAAAAAA=","userData":{"id":"964233534455824475","bot":false,"system":false,"flags":4194304,"username":"0g9","globalName":"Turki","discriminator":"0","avatar":"a_e73b80febc87e42d9a895fba013c3d13","avatarDecoration":null,"avatarDecorationData":null,"createdTimestamp":1649961589207,"defaultAvatarURL":"https://cdn.discordapp.com/embed/avatars/1.png","tag":"0g9","avatarURL":"https://cdn.discordapp.com/avatars/964233534455824475/a_e73b80febc87e42d9a895fba013c3d13.gif","displayAvatarURL":"https://cdn.discordapp.com/avatars/964233534455824475/a_e73b80febc87e42d9a895fba013c3d13.gif"}},"replaceCurrent":false}
INFO 3133875 --- [Lavalink] [ XNIO-1 task-23] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/ju7cslv4cpjtqjq0/players/1263258540831932477?noReplace=false, payload={"track":{"encoded":null},"position":0}
```

and the song start to play
i tried with new ipv4, tried with no ipv6, changed the server fully
still same issue

**Comment by dazzypark** [comment]
show client settings

**Comment by Turkidev** [comment]
server:
  port: 2333
  address: subnet.73

lavalink:
  server:
    password: "password"
    sources:
      youtube: false
      soundcloud: true
      bandcamp: false
      twitch: false
      vimeo: false
      http: false
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 10
    playerUpdateInterval: 2
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.8.2"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.2.0"
      snapshot: false


plugins:
  lavasrc:
    providers: # Custom providers for track loading. This is the default
    sources:
      spotify: true # Enable Spotify source
    spotify:
      clientId: "******************"
      clientSecret: "******************"
      countryCode: "SA" # the country code you want to use for filtering the artists top tracks. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
      playlistLoadLimit: 6 # The number of pages at 100 tracks each
      albumLoadLimit: 6 # The number of pages at 50 tracks each
      localFiles: false # Enable local files support with Spotify playlists. Please note `uri` & `isrc` will be `null` & `identifier` will be `"local"`
  youtube:
    enabled: true # Whether this source can be used.
    allowSearch: true # Whether "ytsearch:" and "ytmsearch:" can be used.
    allowDirectVideoIds: true # Whether just video IDs can match. If false, only complete URLs will be loaded.
    allowDirectPlaylistIds: true # Whether just playlist IDs can match. If false, only complete URLs will be loaded.
    # The clients to use for track loading. See below for a list of valid clients.
    # Clients are queried in the order they are given (so the first client is queried first and so on...)
        clients:
      - MUSIC
      - ANDROID_TESTSUITE
      - WEB
      - TVHTML5EMBEDDED

ratelimit:
  ipBlocks:
    - "oursubnet.73"
    - "oursubnet.74"
    - "oursubnet.75"
    - "oursubnet.76"
    - "oursubnet.77"
    - "oursubnet.78"
    - "oursubnet.79"
    - "oursubnet.80"
    - "oursubnet.81"
    - "oursubnet.82"
  excludedIps: [] # IPs which should be explicitly excluded from usage by Lavalink
  strategy: "LoadBalance" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
  searchTriggersFail: true # Whether a search 429 should trigger marking the IP as failing
  retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
  youtubeConfig: # Required for avoiding all age restrictions by YouTube, some restricted videos still can be played without.
    email: "******************" # Email of Google account
    password: "******************" # Password of Google account


metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
  tags:
    - "tag"
    - "anotherTag"
spotify:
  clientId: "******************"
  clientSecret: "******************"
  countryCode: "SA" # your preferred country code
  
  
  
  
  
  i tried to use another package on my code to get the link for the song and then pass it to lavalink and it works but when i pass the text to lavalink it has the same issue

**Comment by Turkidev** [comment]
where?

**Comment by dazzypark** [comment]
here

```yaml
clients:
- MUSIC
- ANDROID_TESTSUITE
- WEB
- TVHTML5EMBEDDED

**Comment by Turkidev** [comment]
still getting 
INFO 300566 --- [Lavalink] [ XNIO-1 task-42] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:2pac"
INFO 300566 --- [Lavalink] [ XNIO-1 task-42] lavalink.server.player.AudioLoader       : No matches found

**Comment by dazzypark** [comment]
setup oauth

**Comment by Turkidev** [comment]
every song i play it shows kids songs
tried habits it played "Chris learns good habits with Mom | 1 Hour Video - Vlad and Niki"
tried goodbye it played "Goodbye, See You Soon | Goodbye Song for Kids | Treetop Family Children's Song - Super Simple Songs - Kids Songs"

on the old server when i play
goodbye it playes "Ramsey - Goodbye  | Arcane League of Legends | Riot Games Music - Riot Games Music"
habits it playes "Tove Lo - Habits (Stay High) - Tove Lo"

**Comment by JirayuSrisawat-Github** [comment]
![image-35](https://github.com/user-attachments/assets/012f60a8-7068-43bc-8e1a-f79ab29828f9)

Use clients in this order will fix this issue ig

**Comment by topi314** [comment]
`ANDOIRD_LITE` is a typo, it's `ANDROID_LITE`

**Comment by Szprinktrap** [comment]
looks like youtube is now returning 0 results for the `ANDROID_TESTSUITE` client, had the same issue today and putting something else above `ANDROID_TESTSUITE` fixed it

**Comment by devoxin** [comment]
For what it's worth, you can disable certain features of problematic clients

```yaml
clientOptions:
  ANDROID_TESTSUITE:
    searching: false
```

But there are also reports of testsuite not allowing streaming anymore so it might be worthwhile removing the client from your list entirely.

**Comment by devoxin** [comment]
Closing as stale.

The solution for this issue seems to be removing `ANDROID_TESTSUITE` from the client list.
You may also want to remove `ANDROID_LITE` and perhaps `WEB` as these two clients are also debilitated.
