### ISSUE TITLE
Youtube not working: Please sign in

### ISSUE THREAD

**Issue by SuperKali** [lavalink-devs/youtube-source#65]
### Basic Troubleshooting

- [X] I have checked for similar issues, and my issue is not a duplicate. (Check closed issues as well)
- [X] I have checked for pull requests that may already address my issue.
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [X] My issue is reproducible with IPv6 rotation.
- [X] I have confirmed that my issue is reproducible with the minimum viable clients (MUSIC, WEB and TVHTML5EMBEDDED)

### Version of youtube-source

1.8.3

### The search query/queries, URL(s), playlist ID(s)/URL(s) or video ID(s)/URL(s) that triggered the issue

q80GFOfR9Xg

### Code Example

N/A

### Exception and Stacktrace

jmusicbot_superkali | [16:06:25] [WARN] [LocalAudioTrackExecutor]: Suspicious exception for playback of q80GFOfR9Xg
jmusicbot_superkali | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
jmusicbot_superkali | 	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102)
jmusicbot_superkali | 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
jmusicbot_superkali | 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
jmusicbot_superkali | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
jmusicbot_superkali | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
jmusicbot_superkali | 	at java.base/java.lang.Thread.run(Thread.java:829)
jmusicbot_superkali | [16:06:25] [ERROR] [AudioHandler]: Track q80GFOfR9Xg has failed to play
jmusicbot_superkali | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
jmusicbot_superkali | 	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102)
jmusicbot_superkali | 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
jmusicbot_superkali | 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
jmusicbot_superkali | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
jmusicbot_superkali | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
jmusicbot_superkali | 	at java.base/java.lang.Thread.run(Thread.java:829)

### What is your client configuration?

It's a musicbot

**Comment by Korbsti** [comment]
getting the same issue as well
