### ISSUE TITLE
Please sign in error

### ISSUE THREAD

**Issue by Shreya2781235** [lavalink-devs/youtube-source#68]
### Basic Troubleshooting

- [X] I have checked for similar issues, and my issue is not a duplicate. (Check closed issues as well)
- [X] I have checked for pull requests that may already address my issue.
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [X] My issue is reproducible with IPv6 rotation.
- [X] I have confirmed that my issue is reproducible with the minimum viable clients (MUSIC, WEB and TVHTML5EMBEDDED)

### Version of youtube-source

1.8.3

### The search query/queries, URL(s), playlist ID(s)/URL(s) or video ID(s)/URL(s) that triggered the issue

All urls

### Code Example

Sir I my lavalink working fine but suddenly last 1 week I got please sign in error in my lavalink server 

### Exception and Stacktrace

N/A

### What is your client configuration?

Null

**Comment by infnibor** [comment]
Duplicate for https://github.com/lavalink-devs/youtube-source/issues/64
