### ISSUE TITLE
Youtube thumbnail max res.? On Search prefix

### ISSUE THREAD

**Issue by lleans** [lavalink-devs/youtube-source#7]
This may just a misc. thing. Then, when Lavalink has native youtube is working, it used giving a maxres. thumbnail. Which in my case for discord thumbnail, really make a difference.

![image](https://github.com/lavalink-devs/youtube-source/assets/68429210/aff072f9-2180-4ca1-addb-45fd7c225a25)
`Back then` 

![image](https://github.com/lavalink-devs/youtube-source/assets/68429210/b7e0b32a-ea40-4b84-af36-f21674d33371)
`Now`

---

Here the difference on discord embed, absolutely noticeable
![image](https://github.com/lavalink-devs/youtube-source/assets/68429210/a958877a-cadf-46a1-903f-6c66a1db847e)
`before`

![image](https://github.com/lavalink-devs/youtube-source/assets/68429210/bfd7607f-c2e1-4c5d-9b0f-c82b014d936b)
`after`

<br>

It's just simple solution, change the name of the file, from `mqdefault.jpg` into `maxresdefault.jpg`. I've done that on my client, but i just wanted an native solution(properly), which fix from the plugin itself. Thanks.

**Comment by devoxin** [comment]
> change the name of the file, from mqdefault.jpg into maxresdefault.jpg

Doing a manual string replacement is not something we will do within the client itself. Some formats are not guaranteed to exist so this would be potentially breaking behaviour, and in this case a "native solution" is no better than what you do within your own code.

Additionally, YouTube returns thumbnail data within the response JSON which is what we try and extract. If the thumbnail data does not exist, we substitute it with a default that should always (or at least, in the majority of times), be present.
Part of the problem possibly extends from using multiple YouTube clients, which can change the response format that we receive. The existing thumbnail extractor just assumes one static location for thumbnails which might not be the case, hence the lower quality thumbnails.

I have already fixed an issue regarding thumbnail extraction, which was released under the `1.2.0` tag.
Make sure you are running this version.
If you are, please provide the list of InnerTube clients that you are using (this is printed on start-up when using the Lavalink plugin).
Additionally, please provide IDs of the videos that are not returning high resolution thumbnails, that did previously.

**Comment by devoxin** [comment]
This returns `maxresdefault.jpg` for me.
<img width="958" alt="image" src="https://github.com/lavalink-devs/youtube-source/assets/15076404/7bd1aefe-04b5-415c-8f92-2d6c5b837291">

**Comment by lleans** [comment]
Oh..... I think my bad here, sorry. I'm using different youtube link, which is here https://www.youtube.com/watch?v=TGgcC5xg9YI. And just double check it, like you said, it doesn't always have maxres.

Also, the link i gave you, I think I'd test it when using 1.1.0. And just check it with another video, it work. Sorry to bother you. Thanks

**Comment by lleans** [comment]
I think I've found the problem here. While requesting an direct video link, sure it will give me an High res thumbnail. But when requesting an search prefix `ytsearch:query` it doesnt'return high res one(`ytmsearch:query` search function, just work fine).

Using search function.
`ytsearch:pasilyo`
```json
{
  "loadType": "search",
  "data": [
    {
      "encoded": "QAAAywMAL1N1bktpc3NlZCBMb2xhIC0gUGFzaWx5byAoT2ZmaWNpYWwgTHlyaWMgVmlkZW8pAA5TdW5LaXNzZWQgTG9sYQAAAAAABDYgAAtYVG9BLTFkWllXQQABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PVhUb0EtMWRaWVdBAQAwaHR0cHM6Ly9pLnl0aW1nLmNvbS92aS9YVG9BLTFkWllXQS9tcWRlZmF1bHQuanBnAAAHeW91dHViZQAAAAAAAAAA",
      "info": {
        "identifier": "XToA-1dZYWA",
        "isSeekable": true,
        "author": "SunKissed Lola",
        "length": 276000,
        "isStream": false,
        "position": 0,
        "title": "SunKissed Lola - Pasilyo (Official Lyric Video)",
        "uri": "https://www.youtube.com/watch?v=XToA-1dZYWA",
        "sourceName": "youtube",
        "artworkUrl": "https://i.ytimg.com/vi/XToA-1dZYWA/mqdefault.jpg",
        "isrc": null
      },
      "pluginInfo": {},
      "userData": {}
    },
    {}
  ]
}
```

using direct link(same video)
`https://www.youtube.com/watch?v=XToA-1dZYWA`
```json
{
  "loadType": "track",
  "data": {
    "encoded": "QAAA3QMAL1N1bktpc3NlZCBMb2xhIC0gUGFzaWx5byAoT2ZmaWNpYWwgTHlyaWMgVmlkZW8pABFTdW5raXNzZWRMb2xhVkVWTwAAAAAABDI4AAtYVG9BLTFkWllXQQABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PVhUb0EtMWRaWVdBAQA/aHR0cHM6Ly9pLnl0aW1nLmNvbS92aS9YVG9BLTFkWllXQS9tYXhyZXNkZWZhdWx0LmpwZz92PTYzNThmMTk0AAAHeW91dHViZQAAAAAAAAAA",
    "info": {
      "identifier": "XToA-1dZYWA",
      "isSeekable": true,
      "author": "SunkissedLolaVEVO",
      "length": 275000,
      "isStream": false,
      "position": 0,
      "title": "SunKissed Lola - Pasilyo (Official Lyric Video)",
      "uri": "https://www.youtube.com/watch?v=XToA-1dZYWA",
      "sourceName": "youtube",
      "artworkUrl": "https://i.ytimg.com/vi/XToA-1dZYWA/maxresdefault.jpg?v=6358f194",
      "isrc": null
    },
    "pluginInfo": {},
    "userData": {}
  }
}
```


I dont quite understand how you scrap data from youtube. But just letting you know this, or maybe there is fix of it?

**Comment by devoxin** [comment]
I have looked into low quality search thumbnails and have concluded this appears to be working as intended. Search thumbnails seem to be limited to a maximum resolution of 320x180. The code checks whether the extracted thumbnail is high resolution and returns a default that should be equivalent or better than what YouTube returns if it is not, so there's nothing to be fixed here.
