### ISSUE TITLE
Suggestion to modify Author and Title based mostly on the youtube video title

### ISSUE THREAD

**Issue by Vexify4103** [lavalink-devs/youtube-source#8]
Hello,

I've already implemented this feature locally in my bot, but it might be a nice addition in general. Perhaps we could also give users the option to enable or disable this feature using an option in the application.yml file, such as replaceTrackCredentials: true/false.

Many YouTube songs are often uploaded by users who might incorrectly space out the original author's name or include collaborating authors in the title that aren't reflected in the YouTube author field. Here are some examples:

1.
- Song: Purple Disco Machine - Substitution
- Video URL: https://www.youtube.com/watch?v=7x5lqqji9ww
- Actual video title: Purple Disco Machine, Kungs - Substitution (Official Music Video) ft. Julian Perretta
- Current result if any bot uses "track.author - track.title": Purple Disco Machine - Purple Disco Machine, Kungs - Substitution (Official Music Video) ft. Julian Perretta)

2.
- Song: CCR - Fortunate Son (MOONLGHT Remix)
- Video URL: https://www.youtube.com/watch?v=Fg2G8SIb7n4
- Actual video title: CCR - Fortunate Son (MOONLGHT Remix)
- Current result if any bot uses "track.author - track.title": MOONLGHT - CCR - Fortunate Son (MOONLGHT Remix)

3.
- Song: Rarin - GTA
- Video URL: https://www.youtube.com/watch?v=m5wel03bCk4
- Actual video title: Rarin - GTA (Official Lyric Video)
- Current result if any bot uses "track.author - track.title": rarin - Rarin - GTA (Official Lyric Video)

What I'm suggesting is that the plugin compares the video author with the title and then decides (mostly because of the "-") what the author and title are (because the author is in general on youtube videos infront of the dash). This would allow us as bot users to simply use "track.author - track.title" without needing to manually check if the video author is different or includes co-authors.

**Comment by Vexify4103** [comment]
Also I forgot to mention this:
If the video title has no "dash", then just keep it as is

**Comment by devoxin** [comment]
I don't believe this is the duty of the source manager to do. Not only are YouTube title formats generally inconsistent, but occasionally the videos are not uploaded by the artists themselves. This means it's difficult to 'clean' the titles whilst avoiding erroneous string replacements.

For these reasons, I do not think this would be a good idea to include within the source manager/plugin itself. This should remain user-land code so the user can best choose how to proceed with title sanitisation whilst avoiding opinionated replacements done by the source.

**Comment by Vexify4103** [comment]
Same could be also done with youtube videos which are generated:

Remove this if it exists from the author: **- topic**
And remove this if it exists from the title: **Topic -**

**Comment by Vexify4103** [comment]
Ah sry, mb.
I didnt notice you replied already..
