### ISSUE TITLE
New problematic youtube script issue

### ISSUE THREAD

**Issue by AlphaLupine** [lavalink-devs/youtube-source#80]
### Basic Troubleshooting

- [X] I have checked for similar issues (open AND closed), and my issue is not a duplicate. (MANDATORY)
- [X] I have checked for pull requests that may already address my issue. (MANDATORY)
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [X] My issue is reproducible with IPv6 rotation.

### Version of youtube-source

1.8.3 & 1.9.0

### The search query/queries, URL(s), playlist ID(s)/URL(s) or video ID(s)/URL(s) that triggered the issue

https://www.youtube.com/watch?v=X44XAQvODvw&ab_channel=%24uicideboy%24-Topic

### Code Example

N/A

### Exception and Stacktrace

2024-11-30T21:02:10.178Z ERROR 16440 --- [Lavalink] [back-1-thread-1] d.l.y.cipher.SignatureCipherManager      : Problematic YouTube player script /s/player/b46bb280/player_ias.vflset/en_GB/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\Matthew\AppData\Local\Temp\lavaplayer-yt-player-script11485921841717708880.js

Full logs and application.yml example can be found in this thread in the discord lavalink server: https://discord.com/channels/1082302532421943407/1312150965679427627

### What is your client configuration?

WEB, MUSIC, WEBEMBEDDED, ANDROID, IOS

**Comment by devoxin** [comment]
Can't reproduce.
![image](https://github.com/user-attachments/assets/193a4996-6d2b-445e-8e6f-c08d11bc7321)

I don't believe you're running the versions you say you are.

**Comment by AlphaLupine** [comment]
Hi there, please see the following screenshots. 
![Capture1](https://github.com/user-attachments/assets/596c4488-8f93-4818-a687-d3ac1c39a221)
![Capture](https://github.com/user-attachments/assets/3157eb66-ce44-4fa0-986f-7bf55aed9f7b)

**Comment by devoxin** [comment]
Yes. I don't believe that is the version it claims to be. I have tested locally and I do not see any changes in the player script you have linked that would fail to be picked up by the regex.

**Comment by AlphaLupine** [comment]
Ok, I will try manaually downloading the release in that case. If it still fails, I will assume this is some sort of config issue on my end, I appreciate it you taking a look, cheers

**Comment by AlphaLupine** [comment]
After further investgation, I can confiirm that I am using the version specified. Please see the screenshot below showing the contents of the version file from inside the jar in question
![MbXxYwJ](https://github.com/user-attachments/assets/5a0cbb2f-cb4b-4cfa-bbc5-63f7f7bd3d50)
