### ISSUE TITLE
Issue with Jitpack

### ISSUE THREAD

**Issue by DisruptionSystemsINC** [lavalink-devs/youtube-source#81]
### Basic Troubleshooting

- [X] I have checked for similar issues (open AND closed), and my issue is not a duplicate. (MANDATORY)
- [X] I have checked for pull requests that may already address my issue. (MANDATORY)
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [X] My issue is reproducible with IPv6 rotation.

### Version of youtube-source

1.9.0

### The search query/queries, URL(s), playlist ID(s)/URL(s) or video ID(s)/URL(s) that triggered the issue

N/A

### Code Example

N/A

### Exception and Stacktrace

https://jitpack.io/com/github/lavalink-devs/youtube-source/1.9.0/build.log

### What is your client configuration?

N/A

**Comment by topi314** [comment]
We do not use jitpack.
see: https://github.com/lavalink-devs/youtube-source#v2 or https://github.com/lavalink-devs/youtube-source#common on how to add `youtube-source` as a dependency
