### ISSUE TITLE
Suspicious exception for playback of xyz

### ISSUE THREAD

**Issue by KaguyaIndustries** [lavalink-devs/youtube-source#91]
### Basic Troubleshooting

- [X] I have checked for similar issues (open AND closed), and my issue is not a duplicate. (MANDATORY)
- [X] I have checked for pull requests that may already address my issue. (MANDATORY)
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [X] My issue is reproducible with IPv6 rotation.

### Version of youtube-source

1.11.1

### The search query/queries, URL(s), playlist ID(s)/URL(s) or video ID(s)/URL(s) that triggered the issue

ytsearch

### Code Example

N/A

### Exception and Stacktrace

Dez 14 23:45:40 midnight-server java[216894]: 2024-12-14T23:45:40.670+01:00  WARN 216894 --- [Lavalink] [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Suspicious exception for playback of x2btfv_IyUE
Dez 14 23:45:40 midnight-server java[216894]: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video is unavailable
Dez 14 23:45:40 midnight-server java[216894]:         at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:104) ~[youtube-plugin-1.11.1.jar!/:na]
Dez 14 23:45:40 midnight-server java[216894]:         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.2.jar!/:na]
Dez 14 23:45:40 midnight-server java[216894]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.2.jar!/:na]
Dez 14 23:45:40 midnight-server java[216894]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
Dez 14 23:45:40 midnight-server java[216894]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
Dez 14 23:45:40 midnight-server java[216894]:         at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

### What is your client configuration?

      - MUSIC       - WEB       - ANDROID_TESTSUITE       - ANDROID_MUSIC       - TVHTML5EMBEDDED       - ANDROID_LITE       - MEDIA_CONNECT       - IOS

**Comment by devoxin** [comment]
Remove all ANDROID clients. Try with just WEBEMBEDDED and TV, ideally using OAuth.

**Comment by KaguyaIndustries** [comment]
That did the trick! Thank you! <3

**Comment by aikaterna** [comment]
Instead of necroing a closed issue, try making your own.
